[package]
name = "dimensify_widgets"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
bevy_egui.workspace = true
egui_tiles.workspace = true
const-fnv1a-hash = "*"
smallvec = "1.15.1"
