[package]
name = "dimensify_ui"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
bevy_egui.workspace = true
egui_tiles.workspace = true
egui_extras.workspace = true
bevy-inspector-egui.workspace = true
material-design-icons = "7.4.48"
