[package]
name = "dimensify_transport"
version = "0.1.0"
edition = "2024"

[features]
default = []
webtransport = ["dep:lightyear", "lightyear/webtransport"]
websocket = ["dep:lightyear", "lightyear/websocket"]
udp = ["dep:lightyear", "lightyear/udp"]

[dependencies]
bevy.workspace = true
serde = { version = "1.0.210", features = ["derive"] }
thiserror = "1.0.63"
lightyear = { version = "0.25.0", default-features = false, optional = true }
